-- Basic
require('core.plugins')
require('core.configs')
require('core.mappings')
require('core.color')

-- Plugins
require('plugins.mason')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.telescope')
require('plugins.transparent')
require('plugins.null')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.comments')
require('plugins.dash')
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.term')
require('plugins.whichkey')
require('plugins.cursorline')
require('plugins.hop')
require('plugins.fidget')
require('plugins.trouble')
require('plugins.colorizer')
require('plugins.live-server')
